export { checkEmail } from './checkEmail'
export { checkPassword } from './checkPassword'
export { checkNameSurname } from './checkNameSurname'
export { checkQuantity } from './checkQuantity'
export { checkPrice } from './checkPrice'
export { checkProductName } from './checkProductName'